module.exports = {
    NODE_ENV: '"production"',
    FUll_NODE_DEFAULT: '"http://127.0.0.1"',
    PUBLIC_NODE: '"https://api.trongrid.io"',
    FUll_NODE: '"https://api.trongrid.io"',
    NAME_NODE:'"Mainnet"',
    NAME_NODE_CURRENT:'"Shasta"',
    SOLIDITY_NODE: '"https://api.trongrid.io"',
    EVENT_HOST: '"https://api.trongrid.io"',
    NETWORK_ALLOW_LIST: '["https://api.trongrid.io" , "https://api.tronstack.io" , "https://super.guildchat.io"]',
    

    PRIVATE_KEY_ACCOUNT_DEFAULT: '"D10D0FFC9D2EF767E1B34F0892EF06672DC642069B611809E86786F1FF1A8C10"',
    TRONSCAN_URL: '"https://tronscan.org/#/"',
    ETHERSCAN_URL: '"https://etherscan.io/"',
    URL_BACKEND: '"https://api2.zethyr.finance"',
    ADDRESS_DEFAULT: '"T9yD14Nj9j7xAB4dbGeiX9h8unkKHxuWwb"',
    ADMIN_ADDRESS: '"TKnurRAN9jL5cC1b4uqENnQLrSDjub6B38"',
    ztrSwapUSDTContractAddress : '"TSAxtW9bRYAs1de3jkpzCmkZS9ec3uAd1u"',
    ZTR_GET_BALANCE_CONTRACT_ADDRESS:'"TD3PhaDsvqLvuzKjjQodFRg4cYJwf3KbBg"',
    ZTR_DEX_GET_BALANCE_CONTRACT_ADDRESS:'"TMn4pQKB2Mdq7eESN2Po63dmemxXNP2YCH"',
    FEE_LIMIT : '"50000000"' ,// 20 TRX,
    ADMIN_FEE_LIMIT: '"50000000"', //20 TRX,
    USDT_TOKEN_ADDR: '"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"',

 SWAP_WIN_TRX_BINANCE_CONTRACT  : '"TRa7pGxEdpsq6nfCEMEXt7RgrR3k75DZRo"',
    SWAP_WIN_USDT_BINANCE_CONTRACT : '"TRbfgZKg8FiLnZrYYgxcc44kyERFc1sbaS"',
    SWAP_BTT_TRX_BINANCE_CONTRACT  : '"TKa5KB3ScbQYiiGPpPp95cNYh4vjxRPZjk"',
    SWAP_BTT_USDT_BINANCE_CONTRACT : '"TLwAm1DvwLFvhehcybbFEJc4vANzF7hq8M"',
    SWAP_JST_USDT_BINANCE_CONTRACT : '"THWbJbRuyaSHm19B5utpTLZtTNMKBmbbVW"',
    SWAP_SUN_USDT_BINANCE_CONTRACT : '"TG8pz7NZCrRdjsHmS3TECjrU5VsNDhZawn"',
    SWAP_TRX_USDT_BINANCE_CONTRACT : '"TByiA12tVqvsN7cuLXZmgSwRWzpHg7wiTv"',

    JUST_SWAP_WIN_CONTRACT  : '"TF1MwPrv137v1fVavECiAF7TiXrGbbzxRN"',
    JUST_SWAP_BTT_CONTRACT  : '"TKGshLK1gr76URB4RxVYcAf5Uo4fPvHorP"',
    JUST_SWAP_USDT_CONTRACT : '"TWWckpGezEiC7XUfr5SC5rojkEbA1Qay86"',
    JUST_SWAP_JST_CONTRACT  : '"TMjeCitxcsCYvQSdYTpBJpGHb3zs8Kd6Nr"',
    JUST_SWAP_SUN_CONTRACT  : '"TRsvqjamC2wv2E8PqWyVJajrkgHbeUcjbs"',

TOKEN_TRC20_ZTR  : '"TSnym1iciTb53e7vbxDBdEMy9zZWBkvPc6"',
    TOKEN_TRC20_USDT : '"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"',
    TOKEN_TRC20_WIN  : '"TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7"',
    TOKEN_TRC20_JST  : '"TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9"',
    TOKEN_TRC20_SUN  : '"TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9"',
    TOKEN_TRC20_WBTT  : '"TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt"',
    TOKEN_TRC10_BTT  : '1002000',
}
